apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qhsbyfang-python 
  janus-idp.io/tekton: qhsbyfang-python
  backstage.io/kubernetes-id: qhsbyfang-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qhsbyfang-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  